broadinstitute/gnomad_methods

init_scripts/gnomad-init.sh

`pip install --upgrade` also upgrades all dependencies. `slackclient==2.0.0` depends on `idna` and pip (maddeningly) blithely upgrades `idna` to the latest version even though it conflicts with several packages *already installed by pip*.
```
slackclient==2.0.0
- aiodns [required: >1.0, installed: 2.0.0]
- pycares [required: >=3.0.0, installed: 3.0.0]
- cffi [required: >=1.5.0, installed: 1.12.3]
- pycparser [required: Any, installed: 2.19]
- typing [required: Any, installed: 3.6.6]
- aiohttp [required: >3.5.2, installed: 3.5.4]
- async-timeout [required: >=3.0,<4.0, installed: 3.0.1]
- attrs [required: >=17.3.0, installed: 19.1.0]
- chardet [required: >=2.0,<4.0, installed: 3.0.4]
- idna-ssl [required: >=1.0, installed: 1.1.0]
- idna [required: >=2.0, installed: 2.8]
- multidict …
```

Fix Dia's issue

---

utils/gnomad_functions.py

I noticed that the adj expression expects the input data to have only biallelics, but we annotate with adj before splitting multiallelics (https://github.com/macarthur-lab/gnomad_qc/blob/master/sample_qc/generate_hardcalls.py)

Removed hardcoded AD indices from get_adj_expr

---

utils/generic.py

`get_reference_genome` returned the reference genome too early if the input was a locus, so it would never return a reference with sequence

Fixed bug in get_reference_genome

---

utils/sample_qc.py

I decided to have the code check for X and Y for each case, as that made the most sense to me, but I'm open to any feedback!

Automated ploidy cutoffs for karyotype assignment in sample_qc

---

utils/variant_qc.py

Noticed this invalid syntax when trying to build docs.
This function was added in #124 and it looks like the syntax error got introduced in some changes (8ee887fd9216f91a3bdc7683a18beb364fec3f3f) made in response to the initial review.

Fix syntax error in generate_fam_stats_expr

---

resources/variant_qc.py
utils/annotations.py
utils/generic.py
utils/gnomad_functions.py
utils/sample_qc.py
utils/sparse_mt.py
utils/variant_qc.py
utils/variant_qc_plots.py

Some changes to docstrings were necessary to get Sphinx to build docs.
There are still several places that could use some [formatting](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html) improvements, but this is only the minimum change required to resolve all Sphinx's errors and warnings.

Fixup docstrings for Sphinx

---

docs/build.sh

Allow running the docs build script in other shells.

Remove bashism from docs build script

---

.pylintrc
lint

After finding a syntax error (#130) and a few uses of undefined variables, it seems like we could benefit from using a linter.
This adds a configuration file for [Pylint](https://www.pylint.org/) and a wrapper script to eventually be used in some automated checks.
The only non-default configuration in .pylintrc is in the messages control section. This configuration disables refactoring and convention messages (since we have enough errors and warnings to deal with) and also unused-wildcard-import warnings (since wildcard imports are used frequently here, enabling that rule generates thousands of warnings).
To use pylint, install it (`pip install pylint`) and run `./lint`.
If running in an environment without gnomad_hail's dependencies installed, pylint will generate many import related …

Add pylint configuration

---

.github/workflows/ci.yml

This adds a [GitHub Actions](https://help.github.com/en/actions) workflow to build the documentation website on every PR and push to master. On pushes to master, the docs site will be automatically deployed to [GitHub Pages](https://pages.github.com/) by pushing the site to a `gh-pages` branch.

Add workflow to build and publish documentation

---

.github/workflows/ci.yml

Following on from #133, this adds a check to automatically run [Pylint](https://www.pylint.org/) on pushes to master and PRs.
This runs pylint with warning messages disabled. Refactor and convention messages are also disabled by the .pylintrc configuration. Thus, only fatal or error messages (syntax errors, undefined variables, etc) will prevent a PR from passing this status check.

Add job to run Pylint on pushes to master and PRs

---

README.md
docs/generate_api_reference.py

Refer people to the API reference pages instead of the code to browse what's available.
Also increases the depth of the table of contents on that page to make it more useful.

Add link to API reference in README

---

gnomad_hail/resources/grch37/gnomad.py
gnomad_hail/resources/grch38/gnomad.py
gnomad_hail/resources/resource_utils.py
gnomad_hail/utils/annotations.py
gnomad_hail/utils/generic.py
gnomad_hail/utils/gnomad_functions.py
gnomad_hail/utils/ld.py
gnomad_hail/utils/liftover.py
gnomad_hail/utils/plotting.py
gnomad_hail/utils/rf.py
gnomad_hail/utils/sample_qc.py
gnomad_hail/utils/sparse_mt.py
gnomad_hail/utils/variant_qc.py

Fix docstring formatting. For example, without a space between the summary line and parameter list, Sphinx won't format the parameter list.
Also (annoyingly) Sphinx can't parse multi-word types in parameter descriptions. So `:param list of str foo:` has to be replaced with:
```
:param foo:
:type foo: list of str
```
Some time, I'll look into whether it's possibly to pull the parameter types from the type annotations instead of the docstring.

Fixup docstring formatting

---

docs/generate_api_reference.py

If a module or a package has a docstring, display it on that module/package's page in the API reference.

Add module/package's docstring to its API reference page

---

gnomad_hail/resources/grch37/gnomad.py

It was pointing to the coverage paths; it now points to the liftover data paths

Fixed liftover function in grch37

---

docs/README.md

@lfrancioli and I discovered today that the `-d` option for http.server was only added in Python 3.7.
This change replaces the `-d` usage in the instructions for serving the docs locally with `cd` so that the documented command works with Python 3.6. It also adds a note on where to view the docs once the server is running.

Change instructions for serving docs to work with Python 3.6

---

gnomad_hail/resources/resource_utils.py

The type hint and documentation for PedigreeResource's `import_func` argument currently say that it should return a MatrixTable.

Correct type and docs for PedigreeResource's import function

---

setup.py

Because Hail is included in `install_requires` in setup.py, `hailctl dataproc start a-cluster --packages gnomad` always installs the latest PyPI release of Hail. This overwrites any specific Hail version set by the --wheel argument.
This removes Hail from `install_requires` but leaves it in requirements.txt for Actions workflows and easy development setup. 
Resolves #192

Remove Hail from install_requires

---

gnomad/utils/sample_qc.py

This changes min_af, min_callrate,  min_inbreeding_coeff_threshold, and min_hardy_weinberg_threshold to Optional args in get_qc_mt. They are already Optional in filter_rows_to_qc. The global annotations are also updated so None can be passed.

Updates get_qc_mt to accept None on passed args

---

docs/generate_api_reference.py

Currently, in generate_api_reference.py, the top level packages are defined as "resources" and "utils".
This change uses `setuptools.find_namespace_packages` to automatically determine the top level packages. This way, the docs build doesn't need to be updated if we add another one.
This also tidies up the code to determine paths to directories within the repository.

Automatically find packages to build API reference

---

docs/examples/index.rst
docs/examples/vep.rst
docs/index.rst

This adds an Examples section to the documentation with instructions on how to use the gnomAD VEP utilities. (There's possibly a better name for this than "Examples").

Add documentation for using VEP utilities

---

CONTRIBUTING.md
pyproject.toml
requirements-dev.txt

So that formatting is consistent, we should all use the same version and configuration for Black.
* https://black.readthedocs.io/en/stable/installation_and_usage.html#command-line-options
* https://black.readthedocs.io/en/stable/pyproject_toml.html

Add Black configuration

---

CHANGELOG.md
gnomad/utils/slack.py
lint
requirements.txt

A few major changes here:
* Instead of `gnomad.utils.slack` attempting to import a Slack token from a predefined path, the consuming script must now provide the token.
* Replace the `try_slack` functions with a `slack_notifications` context manager. `try_slack` took a function and its arguments as arguments. The context manager allows wrapping Slack notifications around an arbitrary block of code.
* Upgrade the Slack client library from 2.0.0 to 2.5.0.
Usage:
```python
from gnomad.utils.slack import slack_notifications
with slack_notifications("TOKEN", "@user"):
...
```
The second argument can be a username (prefixed with '@') or a channel name (prefixed with '#') to post notifications to.
Tested with the same [legacy test tokens](https://api.slack.com/legacy/custom-integrations/legacy-tok …

Rewrite Slack notifications

---

CHANGELOG.md
gnomad/variant_qc/pipeline.py
gnomad/variant_qc/random_forest.py
gnomad/variant_qc/training.py

This PR is a bit big, but most of it is generalizing or adding functions from gnomad_qc that we will also be using in other pipelines

Add variant QC pipeline functions from gnomad_qc code

---

docs/examples/vep.rst

The VEP example currently uses `--requester-pays-allow-all` to create a cluster. We actually only need to allow the `hail-us-vep` bucket to read VEP configuration from.
https://github.com/broadinstitute/gnomad_methods/blob/0b8e1007aacabcb81e4093d9e315ac6f7c92651b/gnomad/utils/vep.py#L65-L74

Allow specific requester pays bucket in VEP example

---

CHANGELOG.md
docs/examples/vep.rst
gnomad/utils/vep.py

Currently, VEP configuration is downloaded from Hail's US bucket.
https://github.com/broadinstitute/gnomad_methods/blob/2090cbb6672474cdfbfc6ab0a8fb54275fd03499/gnomad/utils/vep.py#L65-L74
This bucket is requestor pays, so reading from it requires that either `--requester-pays-allow-all` or `--requester-pays-allow-buckets hail-us-vep` is specified when starting the cluster. If someone isn't aware of that, it's easy to start a cluster (which takes a fair amount of time with VEP) that can't run the gnomAD VEP utilities.
`hailctl dataproc`'s VEP init scripts download these configuration files and link them to `/vep_data/vep-gcloud.json`. If VEP configuration was loaded from the local copy downloaded by the init scripts instead of the `hail-us-vep` bucket, then the requestor pays arguments …

Use local copy of VEP config

---

CHANGELOG.md
gnomad/resources/grch37/gnomad.py
gnomad/resources/grch37/gnomad_ld.py
gnomad/resources/grch38/gnomad.py
gnomad/utils/vep.py

This is the first resource move to the public requester-pays bucket. The ld resource is 13TB and may take a while to copy. I maintained the same bucket structure as the original bucket.

Updated resource paths to requester pays

---

docs/.gitignore
docs/build.sh
docs/conf.py
docs/copy_changelog.py
docs/index.rst
docs/requirements.txt

Add CHANGELOG.md (minus the "Unreleased" section) to the docs site.
Resolves #235.

Add changelog to docs site

---

CHANGELOG.md
gnomad/sample_qc/relatedness.py
gnomad/variant_qc/evaluation.py
gnomad/variant_qc/pipeline.py

Added changed that were needed in order to run the common code variant QC functions in the UKBB variant QC scripts

Runtime variant QC fixes

---

CHANGELOG.md
gnomad/utils/liftover.py

...also removed now redundant functions

Updated liftover functions to be more generic 

---

CHANGELOG.md
gnomad/variant_qc/evaluation.py

Small change so I can perform the binning easily on only well covered intervals

Allow compute_binned_truth_sample_concordance to compute other bins

---

gnomad/utils/sparse_mt.py

A REF-block may have an end equal to its position. The old code
undercounts depth by treating REF-block intervals as half open, when
they are closed. This change adds in order to get their true size.

Add 1 to REF-block DP expression in impute_sex_ploidy

---

CHANGELOG.md
gnomad/resources/resource_utils.py

This adds a VersionedVersionedTableResource for cases where gnomAD version iterations each have multiple versions of a table. The use case here is metadata ht.

Add VersionedVersionedTableResource

---

gnomad/utils/vcf.py

Changes in 0b6125c3c48e3f44fa433649667abe10059e7c6c broke the docs build. See https://github.com/broadinstitute/gnomad_methods/actions/runs/329380698.
This change:
* Formats with Black
* Fixes the docs build (by adding an empty line between function description and parameters)
* Replaces parameter/return types in docstring with type annotations

Format and fix docs build

---

CHANGELOG.md
gnomad/utils/liftover.py

The current `default_lift_data` doesn't work since `new_locus` is set as `new_locus=lifted_over_locus.result` in `liftover_expr` as below. This PR fixes this error.
https://github.com/broadinstitute/gnomad_methods/blob/ef0fbf3b78ee675b5a94c0673fc28bf6a0960e9c/gnomad/utils/liftover.py#L95-L103

fix default_lift_data

---

CHANGELOG.md
gnomad/utils/sparse_mt.py

Sparse MTs were previously only keyed by locus by default. They are now keyed by locus and alleles by default

densify_sites update

---

gnomad/utils/sparse_mt.py

Using a range inside of an agg_array allocates that range for each
entry. At a site with 4567 alleles, this led to ~12G being allocated.
Doesn't hugely affect runtime, though.

Reduce memory usage of `get_as_info_expr`.

---

CHANGELOG.md
gnomad/resources/grch37/reference_data.py
gnomad/resources/grch38/reference_data.py
gnomad/utils/vep.py

Moved the VEPed context paths out of vep utils and into resources, also turning it into a versioned resource. If we add a VEPed context HT for v101 when fixed then we will need to have versioning. Also changed `vep_or_lookup_vep` to handle the versioning and if a version is not present it will warn the user that it is going to VEP everything from scratch.

Add vep versions

---

CHANGELOG.md
gnomad/assessment/summary_stats.py
gnomad/utils/vep.py

First pass at productionizing some code from https://github.com/macarthur-lab/gnomad_lof/blob/master/constraint/summary_statistics.py

Summary stats

---

CHANGELOG.md
gnomad/variant_qc/evaluation.py
gnomad/variant_qc/pipeline.py

First pass at a PR to fix variant QC evaluation bugs found by Grace and revert back to ranking then binning instead of using approx quantile.

Fixes to variant qc evaluation

---

CHANGELOG.md
gnomad/assessment/summary_stats.py

from https://github.com/macarthur-lab/gnomad_lof/blob/master/constraint/gene_lof_matrix.py#L83. Also added helper functions, but should I move them to another location?

Productionizing `generate_gene_lof_matrix`

---

.pre-commit-config.yaml
CONTRIBUTING.md
requirements-dev.txt

There are [a lot of commits that are just running Black](https://github.com/broadinstitute/gnomad_methods/search?q=black&type=commits).
To save time, this adds a [pre-commit](https://pre-commit.com/) hook that runs Black. After setting it up (`pip install -r requirements-dev.txt`, `pre-commit install`), `git commit` will automatically run Black and the commit will be cancelled if Black made any changes.

Add pre-commit hook to run Black

---

gnomad/utils/vcf.py

These changes allow the user to pass a delimiter when creating and working with frequency labels. v2 used underscores while v3.1 switched to hyphens. This change will allow the code to work with either version and give us flexibility moving forward.

Added delimiter parameter to label functions and those that use them

---

gnomad/assessment/summary_stats.py

(forgot to rename fields in initial PR)

Fixed p calculation in default_generate_gene_lof_summary

---

gnomad/utils/annotations.py
gnomad/utils/plotting.py

On #265, Pylint threw some errors that appear to be false positives (on code that was not changed in the PR).
https://github.com/broadinstitute/gnomad_methods/pull/265/checks?check_run_id=1954044098
The `invalid-unary-operand-type` error has come up before: https://the-tgg.slack.com/archives/C0295AMDW/p1608218693011800

Resolve Pylint errors

---

docs/conf.py
docs/requirements.txt

Currently, we use [intersphinx](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) to link to Hail docs from references to Hail classes, functions, etc. in our docs. However, while that's a nice to have feature, it's not essential. If we can't download `objects.inv` from Hail's website for whatever reason (like if the website is temporarily down) that shouldn't block PR checks or prevent updates to our docs.
Currently, if `https://hail.is/docs/0.2/objects.inv` is unavailable, the docs build will fail. This changes the docs build to check if that file is available before configuring the intersphinx mapping for Hail. If it's not, the docs will build anyway, just without links to Hail docs.

Continue with docs build if unable to download Hail's objects.inv

---

CHANGELOG.md
gnomad/utils/vcf.py

Function previously was not correctly setting metrics to missing on chrY (XX samples only). For example:
```
+----------+---------+
| locus         | alleles     | ac_xx_adj | y_par | y_nonpar | y_conds |
+---------------+-------------+-----------+-------+----------+---------+
| locus<GRCh38> | array<str>  |     int32 |  bool |     bool |    bool |
+---------------+-------------+-----------+-------+----------+---------+
| chrY:2786709  | ["G","T"]   |        NA | false |     true |    true |
| chrY:2786719  | ["C","A"]   |         0 | false |     true |    true |
```
- `y_par` is an annotation showing whether the locus is in a pseudoautosomal region of chromosome Y
- `y_nonpar` is an annotation showing whether the locus is in a non-pseudoautosomal region of chromosome Y
- `y_conds` is an …

Changed or to and in set_female_metrics_to_na

---

gnomad/variant_qc/random_forest.py

Konrad noted that he hit an issue with the current code relying on this import from pyspark that will create issues when moving to spark3.

Change to variant QC json import

---

gnomad/resources/grch37/gnomad.py

A few issues fixed here:
1. Coverage was not recalculated for v2.1.1. That was accounted for in exome resources, but not genome.
2. Similar to 1, there was no liftover dataset created for v2.1. That was accounted for in exome resources, but not genome.
3. Using `remove` to exclude those versions from coverage/liftover resources modified the constant `EXOME_RELEASES`. Thus, after accessing exome coverage resources, v2.1.1 was not available for any other resource that used that constant. For example:
```
from gnomad.resources.grch37 import gnomad
gnomad.coverage("exomes").ht()
gnomad.public_release("exomes").ht()
```
currently throws `KeyError: 'default_version 2.1.1 not found in versions dictionary passed to VersionedTableResource.'`
This changes the `coverage` and `liftover` functions to …

Fix available releases for v2 coverage and liftover

---

.github/workflows/ci.yml

When a commit is made to the default branch, a [GitHub Actions](https://docs.github.com/en/actions) workflow builds the docs site and pushes the site content to the `gh-pages` branch, where it is then picked up by [GitHub Pages](https://docs.github.com/en/pages).
Currently, we use an SSH key stored in repository [secrets](https://docs.github.com/en/actions/reference/encrypted-secrets) together with a [deploy key](https://docs.github.com/en/developers/overview/managing-deploy-keys#deploy-keys) to authenticate the workflow's push to that branch. However, workflows include an [access token](https://docs.github.com/en/actions/reference/authentication-in-a-workflow) for the current repository and the [checkout action](https://github.com/actions/checkout) configures git to use that token for …

Simplify workflow for updating docs site

---

CHANGELOG.md
gnomad/resources/resource_utils.py

Currently, importing a BlockMatrixResource ignores the `overwrite` argument. This passes it through to BlockMatrix.write.
Resolves #266

Use overwrite argument for importing a BlockMatrixResource

---

gnomad/utils/annotations.py

Added two functions from https://github.com/broadinstitute/gnomad-readviz/blob/master/step1__select_samples.py:
`het_hom_hemi_take_expr` (renamed `readviz_struct_expr`) and `hemi_expr`

Added readviz utils

---

gnomad/resources/grch38/gnomad.py

Starting with gnomAD v3.1, we moved from naming release Hail tables `gnomad.{exomes|genomes}.r{version}.sites.ht` to `gnomad.{exomes|genomes}.v{version}.sites.ht`. However, the public release and coverage resources still assume the old convention.
Resolves #350

Fix paths to resources for v3.1+ releases

---

gnomad/resources/grch37/gnomad.py

The default version for gnomAD genome coverage on GRCh37 is set to the current gnomAD release (v2.1.1). However, there is no coverage for v2.1.1 and currently attempting to get that resource throws an error:
```python
from gnomad.resources.grch37 import gnomad
r = gnomad.coverage("genomes")
```
This changes the default version for that resource to v2.1.

Fix default version for GRCh37 genome coverage resource

---

CHANGELOG.md
setup.py

Before Hail moves to Spark 3, @konradjk requested a PyPI release that is known to work with Hail on Spark 2.
https://atgu.slack.com/archives/CNE92R265/p1616678385003600

Release 0.5.0

---

.github/workflows/ci.yml

Now that both #367 and #368 are merged and pydocstyle runs successfully, it can be added to PR checks. This ensures that docstrings follow conventions even if a contributor isn't using the pre-commit hook added in #368.
This also reorders checks so that fast checks (Black and pydocstyle) are run before slower ones (Pylint and pytest). This avoids running the slow checks on PRs that require changes to formatting/docstrings.

Add pydocstyle to PR checks

---

gnomad/resources/resource_utils.py

Each type of resource has some convention for file names (`.ht` for TableResource, `.mt` for MatrixTableResource, etc). Currently, the `__init__` method of BaseResource takes a list of file extensions to use to validate the path and each subclass overloads `__init__` to pass the list of expected file extensions for that subclass.
This moves the list of expected file extensions to a class variable on each subclass, which removes the need to overload `__init__`.

Refactor resource path validation

---

CHANGELOG.md
gnomad/resources/import_resources.py
gnomad/resources/resource_utils.py

The motivation here is to be able to do this:
```
class MyTableResource(TableResource):
def ht(self):
...
resource = VersionedTableResource(
"latest",
{
"latest": MyTableResource(...),
...
}
)
```
Currently, versioned resources require that the class of every version matches one of the base classes of the versioned resource.
https://github.com/broadinstitute/gnomad_methods/blob/763aae935e0de8046a4025f70033b8a1a4e091ed/gnomad/resources/resource_utils.py#L291
Also, accessing an attribute or calling a method on a versioned resource object is effectively the same as accessing the same attribute or calling the same method on the resource object for the default version. Currently, the way this is done is the versioned resource object copies/references all attributes from the resource object for …

Make versioned resources work with subclasses of resource types

---

.github/workflows/ci.yml
.pylintrc

Currently, in PR checks, we disable all Pylint warnings and re-enable a few.
https://github.com/broadinstitute/gnomad_methods/blob/9ce5fdbf5a07e80ea96dc2acb6b5c3943c8f9c97/.github/workflows/ci.yml#L34-L35
This changes Pylint configuration to ignore only the specific warnings that are present in existing code.

Only ignore Pylint warnings that are present in existing code

---

.github/workflows/ci.yml
.pydocstylerc
tests/resources/test_resource_utils.py

Currently, PR checks run pydocstyle on files in the `gnomad` directory.
https://github.com/broadinstitute/gnomad_methods/blob/b5f83b81d42d95d3c1de3bd1b744b363690ac3ac/.github/workflows/ci.yml#L32-L33
Pre-commit hooks, however, run it on all Python files that changed in the commit.
https://github.com/broadinstitute/gnomad_methods/blob/b5f83b81d42d95d3c1de3bd1b744b363690ac3ac/.pre-commit-config.yaml#L15-L18
Thus, it's currently possible for a change to pass PR checks, get merged, and then cause pre-commit hooks to fail when it is pulled locally. This change brings PR checks and pre-commit hooks closer in line by running pydocstyle on tests in PR checks.

Run pydocstyle on tests

---

setup.py

Make the [changelog](https://broadinstitute.github.io/gnomad_methods/changelog.html) easier to find from the PyPI project page.

Add changelog to project URLs on PyPI project page

---

CHANGELOG.md
gnomad/resources/config.py
gnomad/resources/grch37/gnomad.py
gnomad/resources/grch37/gnomad_ld.py
gnomad/resources/grch37/reference_data.py
gnomad/resources/grch38/gnomad.py
gnomad/resources/grch38/reference_data.py
gnomad/resources/import_resources.py
gnomad/resources/resource_utils.py
tests/resources/test_resource_utils.py

This adds support for multiple resource buckets in order to provide access to resources hosted on different cloud providers through our resources framework (#255, #263, #264).
This adds a `GnomadPublicResource` resource class and subclasses for each resource type (`GnomadPublicTableResource`, `GnomadPublicMatrixTableResource`, etc). When reading data, `GnomadPublicResource` rewrite their `path` attribute based on the value of `gnomad.resources.config.gnomad_public_resource_configuration.source`.
Thus, to read resources from `gcp-public-data--gnomad` instead of `gnomad-public-requester-pays`,
```python
from gnomad.resources.config import gnomad_public_resource_configuration, GnomadPublicResourceSource
from gnomad.resources.grch37 import gnomad
gnomad_public_resource_configuration.source = …
```

Support multiple resource buckets

---

.pylintrc
gnomad/resources/resource_utils.py
gnomad/sample_qc/relatedness.py
gnomad/utils/sparse_mt.py
gnomad/variant_qc/evaluation.py
gnomad/variant_qc/training.py

#371 started checking Pylint warnings (previously, we only checked error and fatal level messages) in PR checks. However, some warnings were left ignored because they were present in existing code. This fixes a few of those warnings and removes them from the ignored list.
Descriptions of Pylint messages can be found at https://docs.pylint.org/en/stable/technical_reference/features.html.

Fix some Pylint warnings

---

.pylintrc
CHANGELOG.md
gnomad/utils/annotations.py

Currently, `annotation_type_is_numeric` and `annotation_type_in_vcf_info` do not work.
`isinstance(t, hl.tint32)`, `isinstance(t, hl.tstr)` etc. raise TypeErrors because `hl.tstr`, `hl.int32`, etc. are not Python types (they are instances of a HailType class).
Pylint detects this issue, but we were ignoring this warning.
Related to #378

Fix annotation type helper functions

---

gnomad/resources/resource_utils.py
tests/resources/test_resource_utils.py

Some resources may not be available from all sources due to delays in syncing, etc. In those cases, it would be preferable to provide a helpful error message (directing the user to try reading the resource from the gnomAD buckets) instead of simply letting the read fail.
This wraps all methods of GnomadPublicResource subclasses that read the resource (GnomadPublicTableResource.ht, GnomadPublicMatrixTableResource.mt, etc.) and adds a check for if the resource is available from the selected source. If the resource is not available, an exception with a helpful message is thrown.

Improve error message for when a public resource is unavailable

---

gnomad/utils/annotations.py

When unspecified, `_pops_to_exclude` was throwing an error in the `faf_expr` (`AttributeError: 'dict' object has no attribute 'contains')` and `popmax_expr` functions (`hail.expr.expressions.base_expression.ExpressionException: Hail cannot impute the type of 'None'`). This update sets `_pops_to_exclude` to an empty SetExpression if no value is unspecified for this argument

Fixed pops_to_exclude in faf_expr, popmax_expr

---

gnomad/resources/grch37/gnomad.py
gnomad/resources/grch37/reference_data.py
gnomad/resources/grch38/gnomad.py
gnomad/resources/grch38/reference_data.py
tests/resources/test_resource_utils.py

Files in gnomad-public were moved to gnomad-public-requester-pays.
https://gnomad.broadinstitute.org/news/2021-08-gnomad-hosted-public-files-moved-to-requester-pays-bucket/
This replaces gnomad-public with gnomad-public-requester-pays in resource paths. While going through the resources, I noticed a few (such as VCFs and coverage TSVs) that no longer exist in gnomad-public-requester-pays. We'll have to figure out what to do about those, but that can be done afterward. This at least fixes most of the resource paths.
Resolves #400

Replace gnomad-public bucket in resource paths

---

gnomad/resources/resource_utils.py

Currently, if a resource is not available from the user's selected source, we show an error message directing them to use the gnomAD buckets. However, going forward, we won't host all resource files in our buckets once they are copied to cloud providers' buckets (this is already the case with VCFs).
This generalizes the error message to "try a different source" and adds instructions on how to find a list of all available sources.
Resolves #390
Related to #402

Update error message for when resource is not found in gnomAD bucket

---

gnomad/assessment/__init__.py
gnomad/sample_qc/__init__.py
gnomad/utils/__init__.py
gnomad/variant_qc/__init__.py

I've been trying to figure out why Pylint reports no errors in gnomad_qc despite several v2 scripts importing a function that no longer exists (`gnomad.utils.slack.try_slack`). These module imports in `__init__.py` files seem to confuse Pylint.
I don't think they serve a purpose. It looks like I [suggested them](https://github.com/broadinstitute/gnomad_methods/pull/207#pullrequestreview-382012887) as an alternative to `from module import *`. But I don't think we have any code that relies on them by importing `*` from one of these packages.

Remove module imports from __init__.py files

---

gnomad/utils/file_utils.py

Pylint recently added a new check, unspecified-encoding, which fails on some `open` statements in `file_utils.read_list_data`.
https://pylint.pycqa.org/en/latest/whatsnew/2.10.html

Specify encoding for reading files in file_utils.read_list_data

---

.github/workflows/ci.yml
.github/workflows/publish.yml
CONTRIBUTING.md

When a tag matching `v<VERSION_NUMBER>` is pushed to GitHub, this workflow will publish the tagged code to PyPI. This means that anyone with write access to this repository can publish a new release, as opposed to currently depending on the few team members with PyPI accounts.
Resolves #356

Add workflow to publish to PyPI

---

CONTRIBUTING.md

Clarify that release/version tags should be applied to a commit that is on the master branch and has been pushed to GitHub.

Clarify steps for tagging a new release

---

docs/index.rst
docs/resource_sources.rst

Currently, if a resource is not available from one source, the error message describes how to select a different source (#388, #403). This provides that same information up front on the documentation website.

Document selecting resource source

---

gnomad/utils/filtering.py

Added a vds option to function `subset_samples_and_variants()` @jkgoodrich @klaricch

Modified subset_samples_and_variants()

---

docs/examples/vep.rst
docs/getting_started.rst
docs/resource_sources.rst
gnomad/resources/config.py

Now that all files have been synced to Google Cloud Public Datasets, we can use it as the default source for resources. This will be a more pleasant experience for new users, since they won't have to deal with requester pays.
Resolves #264

Use Google Cloud Public Datasets as default source for public resources

---

.github/pull_request_template.md
.github/release.yml

This [configures automatically generated release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes) to be grouped into sections based on labels applied to pull requests. The [labels](https://github.com/broadinstitute/gnomad_methods/labels) referenced in the configuration have already been created.
This also adds a [pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates) to remind authors about how to include changes in release notes.

Add configuration for generating release notes

---

.github/workflows/publish.yml
CONTRIBUTING.md

The last step in updating the release notes process. Currently, when a version tag (`v#.#.#`) is pushed, the tagged code is automatically published to PyPI. This extends that workflow to also automatically publish a corresponding [GitHub Release](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases) with [release notes generated from pull requests](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes). This minimizes the chances of release notes being accidentally forgotten in the release process. Note that release notes can still be edited from the [Releases page](https://github.com/broadinstitute/gnomad_methods/releases) after the release is published.

Automatically publish GitHub Release with release notes

---

gnomad/resources/config.py
gnomad/resources/resource_utils.py
tests/resources/test_resource_utils.py

Currently, there are options to read gnomAD public resources from either our `gnomad-public-requester-pays` bucket or the Google Cloud Public Datasets `gcp-public-data--gnomad` bucket.
This adds options to read them from the Registry of Open Datasets on AWS S3 bucket or the Azure Open Datasets storage container.
To select a source, use:
```python
from gnomad.resources.config import gnomad_public_resource_configuration, GnomadPublicResourceSource
gnomad_public_resource_configuration.source = GnomadPublicResourceSource.GNOMAD
gnomad_public_resource_configuration.source = GnomadPublicResourceSource.GOOGLE_CLOUD_PUBLIC_DATASETS
gnomad_public_resource_configuration.source = GnomadPublicResourceSource.REGISTRY_OF_OPEN_DATA_ON_AWS
gnomad_public_resource_configuration.source = …
```

Add options for reading public resources from Registry of Open Data on AWS and Azure Open Datasets

---

docs/resource_sources.rst
gnomad/resources/config.py
tests/resources/test_resource_utils.py

Some users may always prefer to use the AWS or Azure copies of gnomAD resources. This allows them to set a default source in an environment variable instead of having to configure it in every pipeline.
Once hail-is/hail#11230 is merged, `get_default_public_resource_source` can be extended to use Hail's guess for the current cloud provider to set the default resource source.
Related to #433

Allow setting the default source for public resources with an environment variable

---

docs/resource_sources.rst
gnomad/resources/config.py
tests/resources/test_resource_utils.py

Follow on to #435. Use the `hl.utils.guess_cloud_spark_provider` function added in hail-is/hail#11230 to set the default source for resources. With this, pipelines running in Azure HDInsight should default to reading resources from Azure Open Datasets.
Resolves #433

Use hl.utils.guess_cloud_spark_provider to set default resources source

---

.pre-commit-config.yaml
requirements-dev.in

I got a pre-commit hook error when trying to commit.
The error was: `ImportError: cannot import name ‘_unicodefun’ from ‘click’ `
[This](https://github.com/psf/black/issues/2964) indicated that I needed to update the version of Black, and after that I was able to add a commit.

Add update to Black version in requirements and pre-commit

---

.github/workflows/publish.yml
CONTRIBUTING.md

Currently, the GitHub Actions workflow for publishing a release assumes that the version is tag is created locally and pushed to GitHub. It automatically creates a corresponding GitHub Release with automatically generated release notes.
https://github.com/broadinstitute/gnomad_methods/blob/00365eb7b11ae1f93ad865f1c56917b04c19006f/CONTRIBUTING.md#publishing-a-release
https://github.com/broadinstitute/gnomad_methods/blob/00365eb7b11ae1f93ad865f1c56917b04c19006f/.github/workflows/publish.yml#L50-L57
However, it's also possible to create a tag through GitHub by manually [creating a GitHub Release](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release).
In that case, the last step of the release workflow fails because a …

Handle tags created through GitHub in publish release workflow

---

.github/workflows/ci.yml

Since renaming the default branch, the CI workflow (Pylint, etc.) is no longer running on commits to main because the workflow configuration still references the master branch.
While the CI workflow is running on PRs, it's also desirable to run it on commits to main since main is the version that's being published and used and it's possible for two concurrent PRs to make changes that pass independently but fail when combined. For example, if one PR added a use of a variable and another PR removed that variable.

Change branch name in CI workflow configuration

---

gnomad/sample_qc/ancestry.py

Only add error_rate, evaluation_sample, and training_sample annotations if "fit" not supplied to assign_population_pcs

Fix to only add the `error_rate` annotation if `fit` is not supplied to `assign_population_pcs`

---

gnomad/sample_qc/filtering.py

We added three new metrics to the VDS sample QC output. This will modify `merge_sample_qc_expr` so that it handles those new annotations appropriately.

Modify `merge_sample_qc_expr` to work with the additional VDS sample QC metrics: n_singleton_ti, n_singleton_tv, and r_ti_tv_singleton

---

gnomad/resources/resource_utils.py

This PR adds a description for the `GNOMAD_PUBLIC_BUCKETS constant`. Our current workflow is to write output data to a requester pays bucket, and all data within the requester pays bucket moves to a separate, non-requester pays public bucket. This workflow isn't super obvious in the repo, so I've added a note here to help clarify.

Added description for GNOMAD_PUBLIC_BUCKETS

---

gnomad/sample_qc/pipeline.py

Allows for some additional QC MT options so that multi-allelic variants and indels can be included if wanted

Add `bi_allelic_only` and `snv_only` options to `get_qc_mt`

---

gnomad/sample_qc/pipeline.py

These edits add a 'partitions' parameter to the `get_qc_mt` function so that MTs can be repartitioned before the LD pruning step

Add n_partitions option to get_qc_mt before LD pruning

---

gnomad/sample_qc/pipeline.py
gnomad/sample_qc/sex.py
gnomad/utils/sparse_mt.py

Modify `get_ploidy_cutoffs` to accept an expression for grouping samples into 'XX' and 'XY' groupings.
Modify `annotate_sex` to allow for sex karyotype imputation to use a gaussian mixture model to determine grouping of samples into 'XX' and 'XY' for use in `get_ploidy_cutoffs`.
Modify `annotate_sex` to make computing f-stat and inferring sex karyotype optional.

Add `gaussian_mixture_model_karyotype_assignment` function to assign sex karyotype using Gaussian mixture models

---

gnomad/utils/constraint.py
gnomad/utils/vep.py

Add generic functions that were in `gnomad_lof` repo.

Add generic constraint functions - annotate_mutation_type(), trimer_from_heptamer(), collapse_strand(), add_most_severe_csq_to_tc_within_vep_root()

---

gnomad/utils/file_utils.py

Add `check_file_exists_raise_error` to use `file_exists` to check the existence of all files in a list of file paths with options to raise an error.

Add more file types to `file_exists` for checking '_SUCCESS'

---

gnomad/sample_qc/pipeline.py

Will currently fail tests because I am waiting on a PR in Hail: https://github.com/hail-is/hail/pull/12195

Add `coverage_mt` option to `annotate_sex` which takes an optional precomputed coverage MT to use for ploidy imputation instead of remaking it.

---

gnomad/sample_qc/ancestry.py

-Resolves issue where the `autosomes_only` filter was ignored if `related_samples_to_drop` was provided to `run_pca_with_relateds`
-Adds an additional_samples_to_drop option to `run_pca_with_relateds`, which will remove additional provided samples when generating the PCs and then project them in the PC space

Add additional_samples_to_drop option to `run_pca_with_relateds`

---

gnomad/utils/file_utils.py

`file_exists()` will crash if it's used on files whose extension is not in `".ht", ".mt", ".bm", ".parquet", ".vds"`, because `paths` isn't assigned. I added `".he"` to the list. Please let me know if you want to add a `else` case dealing with `paths`!

add `.he` to file extensions list in `file_exists()`

---

gnomad/sample_qc/ancestry.py

Currently this will result in an error at this line:
```
pc_cols = [f"PC{i}" for i in pc_cols]
```
because pc_cols is a Hail ArrayExpression.

Fix `assign_population_pcs` error when parameter `pc_cols` is a Hail ArrayExpression

---

gnomad/sample_qc/relatedness.py
requirements.txt

For gnomAD v4 we want to prioritize keeping gnomAD v3.1 release samples so that frequency calculations don't need to be recomputed. The option added in this PR will ensure that these samples are kept when determining what related samples to drop.

Add an option for samples that must be kept to `compute_related_samples_to_drop`

---

gnomad/sample_qc/relatedness.py

Fix `compute_related_samples_to_drop` when `min_related_hard_filter` or `filtered_samples` are used to build a list of additional samples to drop.

Add `get_slope_int_relationship_expr` to get relationship between a pair of samples given slope and intercepts of lines to use as cutoffs.

---

gnomad/utils/file_utils.py

This PR adds a small utility function (`repartition_for_join`) that repartitions a Table to make a downstream join more efficient

Added utility function to repartition HTs prior to join

---

gnomad/utils/annotations.py

Add additional groupings to optional stratified allele frequencies to allow stratified frequencies by multiple annotations: e.g. platform and population, or GATK version and population.

Add additional groupings to optional stratified allele frequencies

---

gnomad/utils/constraint.py

The way context_length is currently determined, there needs to be a full scan through the HT/MT. This allows for a parameter to be passed in instead.
It also throws an error if it finds a 'context' value that is not the expected length. And if no parameter is passed it will detect it using the number of specified values in `num_scan_context_length`.

Modify `annotate_mutation_type` to take optional context length as a parameter.

---

gnomad/utils/annotations.py

This PR expands on the utility of `additional_strata_expr` by allowing the user to pass a list of dictionaries where each dictionary will be grouped together. This relies on the user to define the specific groupings for freq calculations, e.g. [{'pop': pop_expr}, {'platform': platform_expr, 'pop': pop_expr}, {'sample_age_bin': sample_age_bin_expr}]. I think this could eventually be used for all aggregations and clean this function up quite a bit.  I kept the ability to pass a single dictionary but have removed the additonal_strata_groupings_expr as this is a cleaner and more flexible implementation.

Allow any frequency groupings

---

gnomad/utils/annotations.py

Adds the option to pass a callstats struct expression with AC, AN, and the number of homozygote alternates to the inbreeding coefficient expr, allowing someone without access to the GT calls to still calculate inbreeding coefficient.

Add callstats option to inbreeding coeff

---

gnomad/resources/grch38/gnomad.py

"oth" was changed to "remaining" in v4. This adds "remaining" to the groups to remove from popmax.

Add "remaining" to pops to remove for popmax for v4

---

gnomad/utils/annotations.py

This adds an `ab_expr` to  the qual_hists_expr. Currenlt the ab hists rely on AD which is expensive to densify as an array expression of ints. This would allow us to pass a single float expr while maintaining the original AD functionality.

add optional ab_expr to qual_hists

---

gnomad/utils/annotations.py
gnomad/utils/release.py

This adds the ability to merge multiple frequency arrays that are on the same table. The merge supports addition or subtraction of arrays. For subtraction, all freq arrays are subtracted from the first freq array in the list. This also adds a new function to build frequency array dictionaries from the frequency metadata.

Merge freq array function and new frequency dictionary builder

---

gnomad/sample_qc/ancestry.py
requirements.txt

Adds functions `apply_sklearn_classification_model`, `apply_onnx_classification_model` and `convert_sklearn_rf_to_onnx` to support the use of ONNX models as suggested by a user in #533 
Includes fix mentioned in #538 
Test notebook located here: gs://gnomad-julia/notebooks/test_gnomad_ancestry_rf_classification.ipynb
and also attached:
[test_gnomad_ancestry_rf_classification.ipynb.zip](https://github.com/broadinstitute/gnomad_methods/files/11924446/test_gnomad_ancestry_rf_classification.ipynb.zip)

Add parameters `apply_model_func` and `convert_model_func` to `assign_population_pcs` so it has the ability to work with other models types 

---

gnomad/utils/annotations.py

This adds a function to merge histograms that contain the have bin_edges.

Add function to merge histograms with the same bin_edges

---

gnomad/utils/annotations.py

This adds functionality to merge arrays of counts. This is used when merging the array of high AB hets in gnomad_qc's frequency script.

Add option to also merge an array of counts/ints in the freq array merge

---

gnomad/utils/annotations.py
gnomad/utils/filtering.py

This updates annotate_freq to use the added array aggregation functionality in hail, originally added by Tim in #537, adds the ability to add entry aggregation annotations, and generally cleans up the function by splitting the existing annotate_freq into two functions: annotate_freq which calls compute_freq_by_strata. 
This also adds split_vds_by_strata which returns a lists of VDSs with as many VDSs as there are unique values for the passed expression. 
We also add the ability to return a single struct of qual histograms, containing separate structs of raw and adj qual histograms.

Update annotate_freq and qual_hists, add split_vds and compute_freq_by_strata

---

gnomad/sample_qc/relatedness.py
gnomad/utils/annotations.py
gnomad/utils/file_utils.py
gnomad/utils/filtering.py
gnomad/utils/sparse_mt.py
gnomad/variant_qc/random_forest.py

Rewrite remaining invocations of `hl.cond()` to `hl.if_else()`. There are already numerous instances of `hl.if_else()` in gnomad_methods, so this has no compatibility considerations.
Also (in _gnomad/utils/file_utils.py_) import `GoogleStorageAsyncFS` from its modern location. This has been `hailtop.aiocloud.aiogoogle` since hail 2.0.78 (see hail-is/hail#10898 and hail-is/hail#10974). If gnomad_methods needs to be compatible with versions of hail prior to 2.0.78, this part of the change should be omitted.
Very minor, but a few of these appear in our test logs which makes for noise when tracking down other problems via the logs.

Avoid DeprecationWarnings from superseded hail function and import [minor] 

---

gnomad/utils/annotations.py
gnomad/utils/filtering.py

This changes the split_vds_by_strata's return to a dictionary instead of a list of VDSs. This gives more utility in seeing which VDS belongs to which strata. This also fixes a bug in the annotate_freq function.

Split vds change from list to dict

---

gnomad/utils/filtering.py

Script to remove items from the freq array and freq_meta array in the Table.

function to remove items from freq and freq_meta

---

gnomad/utils/annotations.py

If there are more than two freq/freq_meta arrays passed and one of the later arrays has an entry in freq_meta that is not found in one of the first two, it currently returns the wrong result. This will make sure to goo through the set of all freq_meta.

Fix `merge_freq_arrays` for cases with more than two arrays

---

gnomad/utils/annotations.py

I think it misses one case: when set_negatives_to_zero=False & the ann or count >=0, we can just use the original value. Can you check if it makes sense?

fix negative values issue with 'diff'

---

gnomad/utils/annotations.py

Fix for error `Error summary: AssertionError: assertion failed: Key type struct{r: float64} is not a subset of struct{s: str, global_idx: int64, pop_idx: int64}`

Fix `annotate_downsamplings` when used with a Table instead of a MatrixTable

---

gnomad/utils/filtering.py

This adds in an optional filtering of another array that is based on freq_meta (filtering freq_meta_sample_counts is how I will use it)  but I think we could generalize this more since its just adding an optional step with the same exact filtering that happens on freq. Maybe make the function `filter_array_by_meta` or something and pass a dictionary of strings and array expressions that all get filtered the same.....all that said I didnt want to change too much without your inputs since this just went in.

Add optional filter to freq meta sample counts

---

gnomad/utils/annotations.py

Previously the merge function set AF to 0 when AN was 0. This was misleading as it implied coverage/information at these sites.

When merging freq arrays, AF will be missing when AN is 0

---

gnomad/variant_qc/random_forest.py

Update file's apply_rf_model() function to work on GnomAD v4 - still not clear why the prior formulation wasn't working? Will this be a permanent fix , or is it intended to be ? 
JG edit: Current use of `udf` to convert a vector to an array is causing a memory error. `vector_to_array` didn't exist when the original function was written, so this is intended to be a permanent fix that uses a newer function.

Modify `apply_rf_model` to use `vector_to_array` from `pyspark.ml.functions` instead of `udf`

---

gnomad/resources/grch38/gnomad.py
gnomad/utils/annotations.py

- VA freq code needs values from global `ht.freq_index_dict`, but since it's a global and same for every row, it only needs to be read once
- The coverage table only has one row per variant, so it can be joined with the gnomad variant table using a `.join` which is indexed and faster than `.filter`, and makes it so the coverage stats for all the variants in the locus interval can be retrieved in one `.collect` call
- For small-ish tables of tens of thousands of variants or fewer (opposed to millions or more), checkpointing is a significant time overhead to add to what is otherwise relatively fast. So leaving it enabled but having an option to disable it is helpful

Optimize a couple collect calls and add option to disable checkpointing

---

gnomad/utils/annotations.py

Similar to what we do to get a popmax/grpmax from 'freq', we will also get a max on faf95 and faf99 and its corresponding pop from the 'faf' field.

add function to get max FAF from faf_expr

---

gnomad/resources/grch38/gnomad.py

Drops the subsets we didn't make in v4.

Fix v4 subset values

---

gnomad/utils/filtering.py

I have a case where I want to filter my `meta_freq` to 
```
[{'group': 'adj'}, {'group': 'raw'}, {'gen_anc': 'afr', 'group': 'adj'}, {'gen_anc': 'amr', 'group': 'adj'}, {'gen_anc': 'asj', 'group': 'adj'}, {'gen_anc': 'eas', 'group': 'adj'}, {'gen_anc': 'fin', 'group': 'adj'}, {'gen_anc': 'mid', 'group': 'adj'}, {'gen_anc': 'nfe', 'group': 'adj'}, {'gen_anc': 'remaining', 'group': 'adj'}, {'gen_anc': 'sas', 'group': 'adj'}, {'group': 'adj', 'sex': 'XX'}, {'group': 'adj', 'sex': 'XY'}, {'gen_anc': 'afr', 'group': 'adj', 'sex': 'XX'}, {'gen_anc': 'afr', 'group': 'adj', 'sex': 'XY'}, {'gen_anc': 'amr', 'group': 'adj', 'sex': 'XX'}, {'gen_anc': 'amr', 'group': 'adj', 'sex': 'XY'}, {'gen_anc': 'asj', 'group': 'adj', 'sex': 'XX'}, {'gen_anc': 'asj', 'group': 'adj', 'sex': 'XY'}, {'gen_anc': …
```

Add apply_keep_to_only_items_in_filter option to `filter_arrays_by_meta`

---

gnomad/utils/annotations.py
requirements.txt

The VRS module is breaking our loggers. To keep our versions pinned to 0.8.4 and get logging working, we need to move the imports into the functions that use them. This means loggers will only break when using these functions. 
I think what is happening is their init calls logging.BasicConfig without setting a level which will reset the logging level to warning: https://github.com/ga4gh/vrs-python/blob/593508c6e8229336ca1f53a06f69966020cd68f7/src/ga4gh/vrs/__init__.py
I tested this locally and my logging was restored.
It does look like they removed the logging call in later version so another option is to unpin or use another version of vrs in our requirements file.

Move ga4gh imports to their functions

---

gnomad/utils/vcf.py

I got warnings when I tried to use `make_freq_index_dict_from_meta`
```
WARNING (gnomad.utils.release 130): Found unexpected frequency metadata groupings: {'gen_anc'}. 
These groupings are not present in the provided sort_order: ['subset', 'downsampling', 'popmax', 'pop', 
'subpop', 'sex', 'group']. These groupings will not be included in the returned dictionary.
```
Should we make it SORT_ORDER for v3 and v4? And also there are multiple lists of SORT_ORDER in this repo.

Add gen_anc to SORT_ORDER

---

gnomad/assessment/validity_checks.py

This adds pprint of globals and a comparison of associated row and global annotation's lengths. It also opens up monoallelic_expr to accept a dictionary so we can also pass `only_het`. The comp naming is horrible, suggestions welcome. 
I added the new checks to the validate_release_t as well though we wont use it as currently implemented for v4 because we don't want to write out the  annotations required for the global and row annotation comp.

Add pprint globals and a global/row length comparison, updates monoallelic expr in validity checks

---

gnomad/utils/vcf.py

This adds v4 export functionality through a number of fields like `inbreeding_coeff`, new annotations like `grpmax` and `fafmax`, and a `suffix` arg to the info dictionary construction. I tried my best to avoid any breaking change here but the histogram access is one. This is a minor function IMO so I think it is alright and  have assign eda change log ignore label.

v4 VCF export updates

---

gnomad/utils/vcf.py

VCFtools vcf-validator is flagging the VRS_States field. Given the "R", in the header, it expects two entries per field, one for reference, one for alternate. 
```
INFO field at chr1:55064734 .. INFO tag [VRS_States=CA,] expected different number of values (expected 2, found 1)
```
In the release HT, this annotation is ["CA",""] but in the VCF, the empty string is not considered a value. Changing the VCF header to be Number="." allows the number of entries to be variable and pass the vcf-validator.
VCF 4.3 specs
```
• A: The field has one value per alternate allele. The values must be in the same order as listed in the ALT
column (described in section 1.6).
• R: The field has one value for each possible allele, including the reference. The order of the values must be the
reference allele …
```

VRS_States header number from R to .

---

gnomad/utils/file_utils.py

This is function is unused within the group and is breaking imports after hail 0.2.126.

Drop async file exists function

---

gnomad/utils/transcript_annotation.py

Starting to move over generic functions from https://github.com/macarthur-lab/tx_annotation/tree/bea56ddf991607f7479358c0c80588f1a2ec9bc1#applying-transcript-expression-aware-annotation-to-your-own-dataset
This function can take in an expression MT and summarize by transcript and tissue, similar to [this](https://github.com/macarthur-lab/tx_annotation/blob/bea56ddf991607f7479358c0c80588f1a2ec9bc1/tx_annotation_resources.py#L125) function after the loading of the resource.

Add RSEM summary function 

---

gnomad/utils/vep.py

I ran into errors trying to use vep_struct_to_csq on a file that used v101 for vep annotations because the code references some fields not found in vep101. This PR edits the function to avoid errors when using vep v101.

make vep_struct_to_csq compatible with vep 101

---

gnomad/utils/transcript_annotation.py

I removed some things that I don't think should be part of this function and should just be added to some variant HT preprocessing function instead and make this a simple annotation, we could even consider splitting the annotation and the aggregation into two different functions and then add a function that is a wrapper around the preprocess, annotate, and aggregate.
It also has been changed to work with my suggestions in the other PR (though they have not been added here).
I also think the following things should be added to the import function:
```
tx_ht = tx_ht.key_by()
tx_ht = tx_ht.annotate(transcript_id=tx_ht.transcript_id.split("\\.")[0])
tx_ht = tx_ht.key_by(tx_ht.transcript_id)
```
Rename the tissues with ```tissue_id.replace("-", "_").replace(" ", "_").replace("(", …
```

Suggestions to tx_annotate_mt PR

---

gnomad/utils/transcript_annotation.py

This function is similar to [this](https://github.com/macarthur-lab/tx_annotation/blob/bea56ddf991607f7479358c0c80588f1a2ec9bc1/tx_annotation.py#L211C5-L211C30), by taking the proportions of transcript expression to gene expression per tissue, and a mean proportion. It's extended to use both array-format expression data and tissue-as-row expression data as input.

Function to get expression proportion

---

gnomad/sample_qc/ancestry.py

We missed updating "amr" from "Latino" to "Admixed American" in v4.0. This addresses https://github.com/broadinstitute/gnomad_production/issues/1305. 
This also adds "remaining" to the pop_name dict so we do not have to treat it special like we did in v4.0:https://github.com/broadinstitute/gnomad_qc/blob/b87f62a7fba9473b73bee9cea927bf4559fabfb2/gnomad_qc/v4/create_release/validate_and_export_vcf.py#L135

amr dict value description fix

---

gnomad/utils/annotations.py

Also,
Modify `compute_freq_by_strata` to use `agg_by_strata`

Add function `agg_by_strata`, which is a generalized version of the `compute_freq_by_strata`

---

gnomad/utils/sparse_mt.py

The following notebook was used for testing: http://localhost:8123/notebooks/gnomad-julia/gnomad_v4/test_v4_coverage_function_cleanup.ipynb

Clean up `compute_coverage_stats`, change it to use `agg_by_strata` and have an optional `group_membership_ht` parameter

---

gnomad/utils/sparse_mt.py

I have been using this notebook for testing: http://localhost:8123/notebooks/gnomad-julia/gnomad_v4/test_v4_densify_all_reference_sites.ipynb

Add `densify_all_reference_sites` to perform a densify at all sites in a reference HT

---

gnomad/utils/annotations.py
gnomad/utils/sparse_mt.py

Also add a helper function `compute_allele_number_per_ref_site` to use `compute_stats_per_ref_site` to compute AN

Add `compute_stats_per_ref_site` to generalize computation of aggregate stats at all sites in a reference Table

---

gnomad/resources/grch37/reference_data.py
gnomad/resources/grch38/reference_data.py
gnomad/resources/resource_utils.py
gnomad/utils/filtering.py
gnomad/utils/transcript_annotation.py
gnomad/utils/vep.py
setup.py

Modifications: 
- change `process_consequences`, `filter_vep_transcript_csqs` and `preprocess_variants_for_tx` to process and filter variants; 
- move `import_gencode` into `resources_utils.py` since it's versatile in any genome build. 
Additions: 
- `filter_vep_to_gene_list`, `import_gencode`,  and `filter_to_gencode_cds` to filter variants; 
- a few more globals concerning variant consequences in `vep.py`; 
- `tx_filter_variants_by_csqs`, `tx_annotate_variants`, `tx_aggregate_variants` and an ensemble function `perform_tx_annotation_pipeline` to combine the first 3 functions;

Functions to process, filter, annotate and aggregate variants by transcript expression (get the pext scores per variant)

---

gnomad/utils/vcf.py

The adjust_vcf_incompatible_types function does not account for missingness in the int64 -> int32 conversion. Current behavior will make any missing int64 the max int32 value, `2147483647`. This was seen in the v4 exome chrY VCF where the int64 field was converted to int32s but all missing values (homozygote counts  within the freq array for XX groupings on chrY) where made 2147483647. This fixes the function by only converting defined values and leaving them missing otherwise.

Account for missingness in int64 to int32 VCF type conversion

---

gnomad/resources/grch38/gnomad.py
gnomad/utils/vcf.py

The genetic ancestry group Middle Eastern should be considered in `grpmax` and `faf` calculations for v4. This was not considered in v3 so we're splitting these globals into version specific dictionaries where the keys are gnomad versions and values are the genetic ancestry groups. This follows the behavior of POPS.

Add mid to FAF and grpmax calcs

---

gnomad/resources/resource_utils.py

It would be useful to have the option of a repartition on read for existing resources. This adds a `read_args` parameter to the read functions of relevant Resource classes so any additional desired parameters can be passed to the hail read functions. To repartition a HT on read it would just be: `my_resource.ht(read_args={"_n_partitions": 50})`

Add `read_args` parameter to the read functions of Resource Classes

---

gnomad/sample_qc/sex.py
gnomad/utils/annotations.py

I figured there was redundancy in the current code so pulled it out into a function. It probably should be a private module function, `_prep_ploidy_ht`, but since the two functions that use it are in different modules, it seems like not the best practive to import a "private" function so decided against it. Everything else looks good, mostly just a few comments.

Pull ploidy optimization into a function

---

gnomad/utils/vep.py

This change makes an option to not use polyphen_prediction in csq_order and its prioritization score. Test on vep_context 105.

Add option to exclude polyphen from process consequences

---

gnomad/utils/constraint.py

Needed for some plots I am creating that use these two functions on the v4 data

Change `get_downsampling_freq_indices` and `downsampling_counts_expr` to support both 'pop' and 'gen_anc' keys in metadata

---

gnomad/assessment/validity_checks.py

When checks are failing, `generic_field_check` is printing a `show()` of the first rows of the input HT instead of the first few rows that are failing the check

Fix `generic_field_check` in validity_checks.py print of failed checks

---

gnomad/resources/grch38/gnomad.py

Just making this more flexible for the future, there's a warning a few lines above that gnomad_gks() is currently only implemented for gnomAD v4

remove hardcoding of v4 in gnomad_gks

---

gnomad/utils/vep.py

**This adds the following fixes to the current `process_consequences`:**
- There are some things wrong with this part of the code:
```
modifier = _csq_score(tc)
flag_condition = (tc.lof == "HC") & (tc.lof_flags != "")
modifier -= hl.if_else(flag_condition, flag_score, no_flag_score)
modifier -= hl.if_else(tc.lof == "OS", 20, 0)
modifier -= hl.if_else(tc.lof == "LC", 10, 0)
```
- I don't think it is supposed to have `modifier = _csq_score(tc)` since it's already handled by:
```
tcl = tcl.map(
lambda tc: tc.annotate(csq_score=_csq_score(tc) - _csq_score_modifier(tc))
)
```
- Missingness of `.lof` and `.lof_flags` is not handled correctly
- One problem is the same as the one mentioned for the original code
- Another problem is that if `.lof` or `.lof_flags` is missing, `flag_condition` will …

Fix bug in `process_consequences` that was introduced when adding support for VEP without polyphen

---

gnomad/utils/vep.py

Adds: splice_donor_5th_base_variant, splice_donor_region_variant , and splice_polypyrimidine_tract_variant

Update csq impact lists with v105 splice terms

---

gnomad/utils/file_utils.py

Adds a function to create a VDS from GVCFs only. This is mainly a wrapper around hails function with limited utility. We can expand this function's utility to ingest VDS when the time comes and that is needed.

Add create_vds function that only supports creating from gvcfs

---

.pre-commit-config.yaml
gnomad/utils/annotations.py
tests/conftest.py
tests/utils/test_annotations.py

fill_missing_key_combinations: Fill missing key combinations with requested fill values.
missing_struct_expr: Create a struct of missing values for each field and type in the input struct.
Also added test code for both

Add functions `fill_missing_key_combinations` and `missing_struct_expr`

---

gnomad/resources/grch38/reference_data.py

Update default VEP version from 95 to 105, which is the version we used for gnomAD v4/v4.1

Update default vep version for context table resource

---

gnomad/resources/grch38/gnomad.py
gnomad/utils/constraint.py

Add in options to set name for coverage metric and cov_model_type

Add coverage_metric param to allow for different metrics of coverage and cov_model_type option to allow for linear or logarithmic 

---

.github/workflows/ci.yml
gnomad/utils/transcript_annotation.py
tests/resources/test_resource_utils.py
tests/utils/test_transcript_annotation.py

As is, the `ignore_splicing` parameter will remove transcripts from transcript_consequences where the worst consequence in "consequence_terms" is a splicing consequence. However, we want to keep the transcript if it has another consequence in "consequence_terms" that is not a splicing consequence. This PR updates the function so that splicing consequences are removed from the "consequence_terms" before the most severe consequence is added.
Example:
```
"transcript_consequences": [
{
"consequence_terms": [
"splice_region_variant",
"synonymous_variant"
]
}
]
```
Currently this transcript would get removed, but we want it to be kept as:
```
"transcript_consequences": [
{
"consequence_terms": ["synonymous_variant"],
"most_severe_consequence": "synonymous_variant",
}
]
```

Fix `tx_filter_variants_by_csqs` to correctly handle the `ignore_splicing` parameter

---

gnomad/assessment/validity_checks.py

Adds a 'expected_contigs' param to summarize_variants and checks that all the expected contigs are found in the summarize_variants output

Add contig check to summarize_variants

---

gnomad/sample_qc/relatedness.py

As suggested by Chris, we're filtering VDS to trios by `hl.vds.filter_samples`, which will greatly drop the number of variants to the ones with at least one ALT allele in the trio samples; Also, this function has been only used once in gnomad_qc, `annotate_adj` has been used twice before, it will be removed from this function. 
It will not pass the checks if I changed the function name, should I just write another function?

Change filter_mt_to_trios to also filter on vds

---

gnomad/resources/grch38/reference_data.py
gnomad/utils/filtering.py

This copies the import function as for GRCh37 v7, but modified a bit according the current path.

Add import code for GTEx v10 RSEM

---

gnomad/resources/grch37/gnomad.py
gnomad/resources/grch38/gnomad.py

I added pext and constraint resources for both GRCh37 and GRCh38, could you double check the path and version for both?

Add pext and constraint resources

---

gnomad/utils/vep.py

Moving this from another [PR](https://github.com/broadinstitute/gnomad_methods/pull/714) so the functionality can be used sooner

Add `loftee_labels` and `no_lof_flags` parameters to `filter_vep_transcript_csqs_expr` for filtering by loftee labels and flags

---

gnomad/resources/grch37/gnomad.py
gnomad/resources/grch38/gnomad.py

This is to add browser variant and gene tables in gnomad resources. For gene tables, they ran [multiple steps](https://github.com/broadinstitute/gnomad-browser/blob/main/data-pipeline/src/data_pipeline/data_types/gene.py) of transformation to get the intervals for CDS, UTR and exon.

Add browser tables to resources

---

.pre-commit-config.yaml

Before the fix, black, autoped8 and isort would be skipped in pre-commit hooks, says: 
```
check yaml...........................................(no files to check)Skipped
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
black................................................(no files to check)Skipped
autopep8.............................................(no files to check)Skipped
pydocstyle...............................................................Passed
isort................................................(no files to check)Skipped
```
Kristen suggested it might need to be regular expression format for the two folders, and I tested, it's working now.

Make folders in RE for pre-commit config

---

requirements.txt

I ran into this error using the latest release of ONNX 1.18.0 on May 12, 2025: 
```
Traceback (most recent call last):
File "/home/jupyter/packages/gnomad_qc/v5/sample_qc/hard_filters.py", line 7, in <module>
from gnomad.resources.grch38.reference_data import telomeres_and_centromeres
File "/home/jupyter/packages/gnomad/resources/grch38/__init__.py", line 3, in <module>
from .gnomad import *
File "/home/jupyter/packages/gnomad/resources/grch38/gnomad.py", line 15, in <module>
from gnomad.sample_qc.ancestry import POP_NAMES
File "/home/jupyter/packages/gnomad/sample_qc/ancestry.py", line 13, in <module>
from skl2onnx import convert_sklearn
File "/home/jupyter/.local/lib/python3.10/site-packages/skl2onnx/__init__.py", line 16, in <module>
from .convert import convert_sklearn, to_onnx, …
```

Assign ONNX to 1.17.0 to avoid ImportError

---

gnomad/utils/sparse_mt.py
tests/utils/test_sparse_mt.py

PR moves code from within `compute_coverage_stats` to new function `get_coverage_agg_func` to allow for more flexible use of `compute_stats_per_ref_site` (allows for a single call to `compute_stats_per_ref_site` to compute coverage, AN, and qual hists)

Add coverage entry agg function

---

gnomad/utils/annotations.py
tests/utils/test_annotations.py

The current code within `annotate_downsamplings` fails if `gen_anc_expr` isn't specified, despite this being an optional argument.
```
TypeError: annotate_globals: keyword argument 'ds_gen_anc_counts': expected expression of type any, found NoneType: None
```
This PR fixes this issue and also adds tests for this function

Update annotate_downsampling to work without gen_anc_expr

---

gnomad/resources/resource_utils.py
gnomad/utils/constraint.py

This PR updates the GENCODE import and transcript annotation functionality to better handle transcript ID versions and PAR region duplicates.
- When `include_version=True`, the function now properly preserves the full `gene_id` and `transcript_id` including version numbers in separate fields (`gene_id_version` and `transcript_id_version`)
- This allows downstream functions to access both the versioned and non-versioned IDs as needed
- Updated the default `annotations` parameter in `add_gencode_transcript_annotations` to include `start_position` and `end_position` by default
- The function now properly calculates and includes transcript start and end positions from the GENCODE interval data
- Updated documentation to reflect that these annotations are included by default
- Added …

Add `include_version` parameter to `import_gencode` and `remove_y_par` to `add_gencode_transcript_annotations`
