broadinstitute/gnomad_methods

resources.py
* Added population and release standard annotations to get_gnomad_meta
=> * Added release_samples option to get_gnomad_data

resources.py, utils.py
* Some updates to `flatten_struct`: recursive option + OrderedDict
* Added public PC loadings VDS to resources
=> Added functions to unify VDS schemas

resources.py
Added some genome intervals (l277~280)
=> Add some genome intervals (l277~280)

resources.py, utils.py
=> Functions for QC scripts

utils.py
So I don't love this at the moment, since it requires the original VDS (just to calculate the allele frequencies). We could hack our own PCA so that it adds AF into the loadings table, but then you have to use our PCA function in order to use this. Thoughts?
=> pc_project first pass

utils.py
Minor change to annotation name to harmonize with other code in sample_qc pipeline
=> Changing pc_project annotation from 'scores' to 'pca_scores'

resources.py
I'd be down to hide these somewhere (in a class) that you have to explicitly import, but I'm not 100% sure how to do that.
=> Paths for sample QC

resources/basics.py, resources/variant_qc.py, utils/rf.py
* Moved RF to utils
* Added RF run hash path
* Updated rf_parh logic
=> Changes for variant QC / RF

utils/rf.py
* simplify `label_name` / `features` use in `train_rf`
=> * first `key_by()` before `select`

utils/rf.py
=> Added checks for Hail -> Spark fields

utils/gnomad_functions.py
=> RF hash -> gnomad_hail

utils/plotting.py
* Fixed a bug causing problems when data columns weren't first in the dataframe
* Replaced default 6 colors palette with generated palette with up to 256 colors
* Added option to provide color palette (as well as color dict)
* Added tooltips
=> Fixes / enhancements to pair_plot

resources/variant_qc.py, utils/plotting.py, utils/variant_qc_plots.py
Code for the variant QC plots.
Results here:
http://localhost:8123/notebooks/gnomad/variant_qc/public_genomes_qc_plots.ipynb
http://localhost:8123/notebooks/gnomad/variant_qc/public_exomes_qc_plots.ipynb
=> Variant QC plots

resources/basics.py, utils/generic.py, utils/sample_qc.py
WARN: This is currently untested and PR'ed for discussion/review
Added utils/sample_qc.py:
* Much of the gnomAD sample QC made generic and documented
* Some additional functionalities
In generic.py:
* Revised some of the method to broaden their usage
* Added a few functionalities
=> Adding sample QC functionality to the repo

init_scripts/gnomad-init.sh, init_scripts/master-init.sh
=> Echo each command for easier debugability.

utils/sample_qc.py
similar in spirit to moving that `sklearn` import
=> move hdbscan import into function

utils/generic.py
Whoever is going to review this should double-check the logic against GATK (URL in comment)
=> Added from/to phred and FS computation from SB annotation

utils/sample_qc.py
renamed `inbreeding_coeff_threshold` arg for consistency.
=> Added HWE test p-value to qc_mt.

resources/basics.py, utils/generic.py
Adding vep_or_lookup_vep, some paths to resources, and a minor fix to process_csq in light of OS
=> Some VEP resources

utils/generic.py
- Added doc
- Format floats to 3 decimals
=> Small changes to VEP struct to CSQ:

utils/sample_qc.py
- Removed double negative (changed `GT_not_called` to `GT`)
- Changed grouping to account for non-unique intervals/interval names
=> Updated compute_callrate_mt in sample_qc.py 

resources/basics.py, resources/variant_qc.py
Removed it from coverage_ht_path
=> Added `grouped` to coverage_mt_path

utils/sparse_mt.py
to run sex imputation on a sparse exomes MatrixTable
=> Added calling intervals impute_sex_ploidy 

utils/liftover.py
Fixed unassigned variable `build`
=> Fixed bug in block of code under args.test of liftover.py

gnomad_hail/resources/grch37/reference_data_import.py, gnomad_hail/resources/grch38/gnomad.py, gnomad_hail/resources/grch38/reference_data.py, gnomad_hail/resources/grch38/reference_data_import.py
- Relative -> absolute imports for reference data imports to ease running them
- Removed a few stray commas
=> Added remaining gnomad v3 public resources

gnomad_hail/resources/resource_utils.py
- A few minor non-breaking changes to how the `expected_file_extension` argument is used
=> Addition of LazyTableResource for resource that are imported at runtime

requirements.txt, setup.py
This lays the groundwork for publishing on PyPI.
* https://packaging.python.org/tutorials/packaging-projects/#creating-setup-py
* https://packaging.python.org/guides/distributing-packages-using-setuptools/
=> Add setup.py

gnomad_hail/resources/grch38/reference_data.py
Added a vep step to the clinvar import per Beryl's suggestion.
=> add vep to clinvar import

gnomad_hail/utils/annotations.py, gnomad_hail/utils/constants.py
from gnomad_qc (https://github.com/macarthur-lab/gnomad_qc/blob/master/gnomad_qc/v2/variant_qc/make_var_annot_hists.py)
=> Moved variant annotation hists functions to gnomad_hail

gnomad_hail/utils/sparse_mt.py
=> Added info ht calculation and split info ht functionality

gnomad_hail/resources/grch38/reference_data.py
=> Small change to add version to syndip and file paths

gnomad_hail/utils/generic.py
=> Another really small PR changing use of resources in `filter_low_conf_regions`

gnomad/utils/sparse_mt.py
Just came across a small bug when testing
=> Small bug fix to default_compute info

gnomad/sample_qc/relatedness.py, gnomad/utils/annotations.py, gnomad/utils/liftover.py, gnomad/utils/plotting.py
Formatted four files that vscode black failed to format with black. Used the command line black to format this time and moving forward.
=> Ran command line black to format

.github/workflows/ci.yml
Require Black formatting in PRs.
=> Add formatting check to workflow

init_scripts/master-init.sh
Note: this is already the init script in gs://gnomad-public/tools/inits/
=> gnomad_hail -> gnomad_methods in master init script

CHANGELOG.md, gnomad/utils/slack.py
Add docstring with example usage for `gnomad.utils.slack.slack_notifications`.
=> Document slack_notifications function

.github/workflows/ci.yml
Attempting to resolve or at least reproduce the PySpark install error in checks on #241.
https://github.com/broadinstitute/gnomad_methods/pull/241/checks?check_run_id=929532907
=> Update cache and setup-python Actions

CHANGELOG.md, gnomad/utils/vcf.py
...to RF_FIELDS and make_hist_dict
=> Added small fixes 

setup.py
This email is displayed in the "Meta" section of the sidebar on PyPI.
https://pypi.org/project/gnomad/
=> Update author email

CHANGELOG.md, gnomad/resources/resource_utils.py
Removes VersionedVersionedTableResource class and also sorts imports.
=> Removes VersionedVersionedTableResource class

gnomad/resources/grch38/reference_data.py, gnomad/resources/resource_utils.py
Small PR to add new dbSNP release to resources
=> Add dbSNP B154 to resources

gnomad/resources/grch38/gnomad.py
Tiny review to go along with https://github.com/broadinstitute/gnomad_qc/pull/139 (needed to pass PyLint checks)
=> Adding new constants for generating frequency data

gnomad/utils/annotations.py
Added `sample_group_filters_range_array` annotation (following format of fix in `default_compute_info`) https://github.com/broadinstitute/gnomad_methods/blob/master/gnomad/utils/sparse_mt.py#L454
=> `annotate_freq` update

gnomad/assessment/summary_stats.py
The if statements are super ugly, I couldn't think of a cleaner way to write this
=> Actually fixed bug in consequence filtration

gnomad/assessment/sanity_checks.py
For use in UKBB QC and gnomAD QC
=> Add `compare_row_counts` to sanity checks

gnomad/utils/annotations.py
Requested as an addition to gnomAD release HT
=> Add sample count global in `annotate_freq`

.github/workflows/ci.yml, CONTRIBUTING.md, lint, pytest.ini, requirements-dev.txt, tests/resources/test_resource_utils.py
Configure PR checks to run tests using [pytest](https://docs.pytest.org/en/stable/) and add a few tests for resource classes.
=> Add tests to PR checks

.github/workflows/ci.yml, gnomad/assessment/sanity_checks.py, gnomad/assessment/summary_stats.py, gnomad/sample_qc/ancestry.py, gnomad/sample_qc/filtering.py, gnomad/sample_qc/pipeline.py, gnomad/sample_qc/platform.py, gnomad/sample_qc/relatedness.py, gnomad/sample_qc/sex.py, gnomad/utils/annotations.py, gnomad/utils/filtering.py, gnomad/utils/gen_stats.py, gnomad/utils/liftover.py, gnomad/utils/reference_genome.py, gnomad/utils/sparse_mt.py, gnomad/utils/vcf.py, gnomad/utils/vep.py, gnomad/variant_qc/evaluation.py, gnomad/variant_qc/pipeline.py, gnomad/variant_qc/random_forest.py, gnomad/variant_qc/training.py
Fixing problem identified by Nick https://github.com/broadinstitute/gnomad_methods/pull/360#discussion_r610097958
=> Fix logging statements to not use f-strings or .format

gnomad/assessment/validity_checks.py
Found a small issue when testing on the HGDP + TGP subset VCF export
=> Sanity check fix for subsets

CHANGELOG.md, setup.py
Update version number and changelog.
=> Version 0.6.0

init_scripts/vep101-init.sh
Added to resolve https://github.com/broadinstitute/gnomad_methods/issues/271
=> Add VEP 101 init

gnomad/utils/release.py
A quickie for anyone who is available today
=> Small fix to docstrings for make_freq_index_dict()

gnomad/sample_qc/pipeline.py
Add option for setting the block size for LD pruning within  get_qc_mt
=> Add block_size option to get_qc_mt for LD pruning

gnomad/resources/resource_utils.py, gnomad/utils/vep.py
=> Fix `vep_or_lookup_vep` to drop `vep_proc_id` if it exists

gnomad/resources/grch38/reference_data.py
updates the paths within import_args for certain resources to use the gcp public bucket
=> update the paths within import_args to use the gcp public bucket for grch38

setup.py
First step in creating the v0.6.3 release
=> Change setup.py version to 0.6.3 for new release

.pre-commit-config.yaml, requirements-dev.in
=> update pre-commit hooks

.pre-commit-config.yaml, docs/requirements.docs.txt, requirements-dev.in, requirements-dev.txt
Forgot to run pip-compile on the modified .in file
=> Run pip-compile to update requirements-dev.txt and requirements.docs.txt

gnomad/resources/grch38/gnomad.py
=> v4 definitely has NFE

gnomad/sample_qc/relatedness.py
`sample_list_stratification` is an optional dictionary with samples as keys and a value that should be used to stratify samples in `sample_list` into groups that the trio should be picked from. This ensures that each fake trio will contain samples from only the same stratification. For example, if all samples within a fake trio should be chosen from the same platform, this can be a dictionary of sample: platform.
=> Add `sample_list_stratification` option to `create_fake_pedigree` function

gnomad/utils/annotations.py
This is a breaking change but this is so new that I doubt it's being used outside of our group. This just allows more than a single count array annotation to be merged at the same time. I'll use it to merge the freq meta sample counts. We could add the option to just pass a single list, so union on count arrays and convert it to a dict if you think that would be better.
=> Run count merge through dict of lists rather than single list

gnomad/variant_qc/random_forest.py
Fixes an error in `apply_rf_model` that resulted in some missing prediction values by adding back in the write to a temp parquet file.
=> Add back write to parquet file in `apply_rf_model` and make `label` parameter optional

gnomad/utils/annotations.py
This fixes the histogram logic for NAs. The hl.zip().map() was making every histogram an NA whenever there was a missing value for a histogram, i.e. the value was not found in the subset. This is because value + missing = missing. We also did not have fill_missing=True so we did value + NA a lot. The hl.or_else() statement also requires the `hl.literal([hl.missing(hl.tint)]))` not just a `hl.missing(hl.tarray...` because then we are back to adding value + missing. The way implemented here creates an empty list, not a missing empty list.  The `bin_edges` also needed fixing in the case a variant wasnt present in a subset. Sorry my testing didnt catch this.
=> Fix merge_histograms for NAs

gnomad/variant_qc/vqsr.py, gnomad/variant_qc/vqsr_resources.json
Hardcoded a few things for testing that will need to be changed
=> Changes made to get preliminary v4 vqsr results

gnomad/utils/annotations.py
Needed for changes in gnomad_qc [PR](https://github.com/broadinstitute/gnomad_qc/pull/450)
=> Add helpful parameters to `generate_freq_group_membership_array` and `compute_freq_by_strata`

gnomad/utils/annotations.py
I added on to your function so it works on any threshold in faf.
=> Add ability to retrieve max for any threshold in faf

docs/requirements.docs.txt, requirements-dev.txt, requirements.txt
Ran
```
pip-compile requirements-dev.in --upgrade
pip-compile docs/requirements.docs.in --upgrade
```
to update our requirements files
=> Update requirements files

gnomad/resources/grch38/gnomad.py
Related to: https://github.com/broadinstitute/gnomad_qc/pull/550
=> Add gnomAD all sites allele number resource

gnomad/sample_qc/sex.py
=> Change null to missing in `adjusted_sex_ploidy_expr`

gnomad/utils/constraint.py
=> Small docstring edits for mane_select

gnomad/utils/vcf.py
Add the stat union and its descriptions for the joint release HT to VCF.
=> Add Stat Union to the info dict

gnomad/utils/vcf.py
Fixes a bug in the new joint feature of `make_vcf_filter_dict` that we missed.
=> Fix bug in joint filter dict

gnomad/utils/file_utils.py
This adds the ability to pass a list of VDSes to the combiner function.
=> Add vds list option to create vds

gnomad/resources/grch38/gnomad.py, gnomad/sample_qc/relatedness.py
"joint" wasn't included in the public release or DATA_TYPES.
=> Add joint to public release

gnomad/assessment/parse_validity_logs.py, gnomad/assessment/validity_checks.py, tests/assessment/test_validity_checks.py
add "subsets": ["non_ukb"], to config file for testing
=> Exclude zero value comparisons from compare_subset_freqs, add retired term check, add filter check, change default delim

gnomad/sample_qc/ancestry.py
Add partition param to assign_population_pcs, previously was creating table with only 2 partitions
=> Add partition param to assign_population_pcs
